---
title: "Lab 2 Pt2"
output: html_document
---

> Let's apply some of the syntax we've learned this week to some problems.
> This should be similar to Problem Set 1, but be warned that the data is different.

---

Your problem set is based on resources produced by Elena Llaudet and Kosuke Imai. It draws on the data and research in the following publication:

Raghabendra Chattopadhyay and Esther Duflo. 2004. “Women as Policy Makers: Evidence from a
Randomized Policy Experiment in India." Econometrica, 72 (5): 1409–43.)

In this article, the authors conduct an experiment in India, randomly assigning villages to have a female council head. The dataset we will be analyzing is in a file called [“india2.csv”](https://github.com/yuanzhouwang/yzwang-teaching/blob/main/india2.csv). This is further modified from "india.csv".

---

## Getting Started

Read the CSV file ["india2.csv"](https://github.com/yuanzhouwang/yzwang-teaching/blob/main/india2.csv) into an object called `india2`. Read the first few observations of the dataset.

-   What does each observation in this dataset represent?
-   Please substantively interpret the first observation in the dataset.
-   What is the **type** of each variable in the dataset?

---

## Exploratory Data Analaysis

How many observations are in the dataset? What does this mean, substantively?

What percent of villages surveyed had a female politician?

On average, how many new or repaired drinking water facilities were built in each village surveyed?

---

## Methodology
We want to estimate the *average causal effect* of having a female politician on the number of
new (and repaired) drinking water facilities:
1. What would be the treatment variable?
2. What would be the outcome variable?
3. What would be the treatment group?
4. What would be the control group?

We also wanted to estimate the average causal effect of having a female politician on the number of
new (and repaired) irrigation facilities:
1. What would be the treatment variable?
2. What would be the outcome variable?
4. What would be the control group?